# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Truco Marcador' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Truco Marcador
  pod "Google-Mobile-Ads-SDK"
pod 'SwiftyStoreKit'
pod "InAppPurchase"
pod "InAppPurchase"
pod 'MerchantKit'
  target 'Truco MarcadorMockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Truco MarcadorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
